import type { VehiclePreview } from "@/types/vehicle";

/**
 * Véhicules d'exemple, en attendant le vrai inventaire (modèle Prisma +
 * saisie via l'administration). À remplacer par une requête à la base
 * de données une fois le modèle Vehicle en place.
 */
export const PLACEHOLDER_VEHICLES: VehiclePreview[] = [
  {
    id: "1",
    brand: "Peugeot",
    model: "208",
    version: "1.2 PureTech Active",
    year: 2021,
    mileageKm: 42000,
    fuel: "Essence",
    transmission: "Manuelle",
    powerHp: 100,
    color: "Blanc",
    price: 14990,
    status: "available",
    isNew: true,
    createdAt: "2026-07-18",
  },
  {
    id: "2",
    brand: "Volkswagen",
    model: "Golf",
    version: "1.6 TDI Comfortline",
    year: 2019,
    mileageKm: 78000,
    fuel: "Diesel",
    transmission: "Manuelle",
    powerHp: 115,
    color: "Gris",
    price: 15490,
    status: "available",
    createdAt: "2026-06-02",
  },
  {
    id: "3",
    brand: "Kia",
    model: "Sportage",
    version: "1.6 CRDi Drive",
    year: 2020,
    mileageKm: 63000,
    fuel: "Diesel",
    transmission: "Automatique",
    powerHp: 136,
    color: "Noir",
    price: 19990,
    status: "reserved",
    createdAt: "2026-05-20",
  },
  {
    id: "4",
    brand: "Renault",
    model: "Clio",
    version: "TCe Zen",
    year: 2022,
    mileageKm: 21000,
    fuel: "Essence",
    transmission: "Manuelle",
    powerHp: 90,
    color: "Rouge",
    price: 15990,
    status: "available",
    isNew: true,
    createdAt: "2026-07-22",
  },
  {
    id: "5",
    brand: "Toyota",
    model: "Yaris",
    version: "Hybrid Dynamic",
    year: 2021,
    mileageKm: 35000,
    fuel: "Hybride",
    transmission: "Automatique",
    powerHp: 116,
    color: "Blanc",
    price: 17990,
    status: "available",
    createdAt: "2026-06-28",
  },
  {
    id: "6",
    brand: "Citroën",
    model: "C3",
    version: "PureTech Feel",
    year: 2018,
    mileageKm: 89000,
    fuel: "Essence",
    transmission: "Manuelle",
    powerHp: 83,
    color: "Bleu",
    price: 10990,
    status: "available",
    createdAt: "2026-04-15",
  },
  {
    id: "7",
    brand: "Opel",
    model: "Corsa",
    version: "1.2 Edition",
    year: 2020,
    mileageKm: 54000,
    fuel: "Essence",
    transmission: "Manuelle",
    powerHp: 75,
    color: "Gris",
    price: 12490,
    status: "sold",
    createdAt: "2026-03-10",
  },
  {
    id: "8",
    brand: "Dacia",
    model: "Sandero Stepway",
    version: "Essential",
    year: 2022,
    mileageKm: 18000,
    fuel: "Essence",
    transmission: "Manuelle",
    powerHp: 90,
    color: "Orange",
    price: 13490,
    status: "available",
    isNew: true,
    createdAt: "2026-07-10",
  },
  {
    id: "9",
    brand: "Ford",
    model: "Focus",
    version: "1.5 EcoBlue ST-Line",
    year: 2019,
    mileageKm: 71000,
    fuel: "Diesel",
    transmission: "Manuelle",
    powerHp: 120,
    color: "Noir",
    price: 14990,
    status: "reserved",
    createdAt: "2026-05-05",
  },
  {
    id: "10",
    brand: "Hyundai",
    model: "Tucson",
    version: "1.6 CRDi Feel",
    year: 2020,
    mileageKm: 58000,
    fuel: "Diesel",
    transmission: "Automatique",
    powerHp: 136,
    color: "Blanc",
    price: 20990,
    status: "available",
    createdAt: "2026-06-14",
  },
];
